nodes:
  Rubik's Cube_8:
    links: {}
    name: Rubik's Cube_8
    nodeClass: Rubik's Cube
    values: {}
  Skateboard_6:
    links: {}
    name: Skateboard_6
    nodeClass: Skateboard
    values: {}
  Yo-yo_5:
    links: {}
    name: Yo-yo_5
    nodeClass: Yo-yo
    values: {}
  Playdough_7:
    links: {}
    name: Playdough_7
    nodeClass: Playdough
    values: {}
  Bubbles_10:
    links: {}
    name: Bubbles_10
    nodeClass: Bubbles
    values: {}
  Weight_12:
    links:
      Generator:
        - outputPort: Generator
          sourceNode: Color Variation_11
    name: Weight_12
    nodeClass: Weight
    values:
      Weight: '4'
  Color Variation_11:
    links:
      Generators:
        - outputPort: Bubbles Bottle Generator
          sourceNode: Bubbles_10
        - outputPort: Play Dough Generator
          sourceNode: Playdough_7
        - outputPort: Skateboard Generator
          sourceNode: Skateboard_6
        - outputPort: Yoyo Generator
          sourceNode: Yo-yo_5
    name: Color Variation_11
    nodeClass: Color Variation
    values:
      Color: <random>
  Container_3:
    links: {}
    name: Container_3
    nodeClass: Container
    values:
      Container Type: <random>
  Floor_9:
    links: {}
    name: Floor_9
    nodeClass: Floor
    values:
      Floor Type: <random>
  Light_2:
    links: {}
    name: Light_2
    nodeClass: Light
    values:
      Location (m): "[0.0, 0.0, 2.0]"
      Radiant Power (W): 100
      Type: SPOT
  50mm Camera_4:
    links: {}
    name: 50mm Camera_4
    nodeClass: 50mm Camera
    values:
      Location Height (m): 0.5
      Roll (degrees): 0
  Place Over Container_0:
    links:
      Container Generator:
        - outputPort: Container Generator
          sourceNode: Container_3
      Floor Generator:
        - outputPort: Floor Generator
          sourceNode: Floor_9
      Object Generators:
        - outputPort: Rubik's Cube Generator
          sourceNode: Rubik's Cube_8
        - outputPort: Generator
          sourceNode: Weight_12
    name: Place Over Container_0
    nodeClass: Place Over Container
    values:
      Number of Objects: 25
  Render_1:
    links:
      Camera:
        - outputPort: Camera
          sourceNode: 50mm Camera_4
      Lights:
        - outputPort: Light
          sourceNode: Light_2
      Objects of Interest:
        - outputPort: Objects of Interest
          sourceNode: Place Over Container_0
    name: Render_1
    nodeClass: Render
    values:
      Calculate Obstruction: F
version: 2
